node:punycode:52
	throw new RangeError(errors[type]);
	^

RangeError: Invalid input
    at error (node:punycode:52:8)
    at Object.decode (node:punycode:*:*)
    at Object.<anonymous> (*test*message*core_line_numbers.js:*:*)
    at Module._compile (node:internal/modules/cjs/loader:*:*)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:*:*)
    at Module.load (node:internal/modules/cjs/loader:*:*)
    at Function.Module._load (node:internal/modules/cjs/loader:*:*)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:*:*)
    at node:internal/main/run_main_module:*:*
