node:events:*
      throw er; // Unhandled 'error' event
      ^

Error
    at Object.<anonymous> (*events_unhandled_error_nexttick.js:*:*)
    at Module._compile (node:internal/modules/cjs/loader:*:*)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:*:*)
    at Module.load (node:internal/modules/cjs/loader:*:*)
    at Function.Module._load (node:internal/modules/cjs/loader:*:*)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:*:*)
    at node:internal/main/run_main_module:*:*
Emitted 'error' event at:
    at *events_unhandled_error_nexttick.js:*:*
    at processTicksAndRejections (node:internal/process/task_queues:*:*)
